### ISSUE TITLE
EBASE with no air-sea diffusion

### ISSUE THREAD

**Issue by sjbalint** [fawda123/EBASE#10]
There are cases where a researcher may want to estimate production and respiration with no air-sea diffusion, such as for a sonde that is located at the bottom of the water column. In the comparable ecometab() function from the WtRegDO package, this feature is accomplished by setting bott_stat=TRUE. It is possible to approximate the result using the following code, but it is clunky, and a dedicated option to remove air-sea diffusion would be more intuitive.

```r
library(EBASE)
library(dplyr)
library(lubridate)
library(doParallel)

# get four days of data
dat <- exdat %>%
  filter(month(DateTimeStamp) == 6 & day(DateTimeStamp) %in% 1:4)

##
# run ebase with defaults

# setup parallel backend
cl <- makeCluster(2)
registerDoParallel(cl)

res <- ebase(dat, interval = 900, Z = 1.85, bprior=c(0, 0.001))

stopCluster(cl)

```

**Comment by fawda123** [comment]
@sjbalint thanks for this, I'll need to consider if this is reasonable since it would involve substantial reworking of several of the EBASE functions, in addition to the core JAGS model file.  Seems like the workaround you provided is a good option.  Is there anything especially problematic with this approach?

**Comment by sjbalint** [comment]
@fawda123 My approach works, it is just not immediately intuitive... if `bprior=c(0,0)` the function returns an error that is difficult to trace. I wonder if an option similar to `bott_stat` could be included that would overwrite `bprior` with values that approximate zero?

**Comment by fawda123** [comment]
Ah I see what you mean, the JAGS errors in the R console aren't helpful at all.  I think adding an argument that just zeroes out the prior would work.  I can add that soon. 

Also note that v1.0.2 was pushed to CRAN today.  This includes a bug fix if using a continuous tidal height vector for the `Z` argument in `ebase()`.

**Comment by fawda123** [comment]
@sjbalint check it out, `bprior = c(0, 1e-8)` if `nogas = T`:  

```r
library(EBASE)
library(dplyr)
library(lubridate)

# subset four days in June
dat <- exdat %>%
  filter(month(exdat$DateTimeStamp) == 6 & day(exdat$DateTimeStamp) %in% 1:4)

res <- ebase(dat, interval = 900, Z = 1.85, n.chains = 2, nogas = T)

ebase_plot(res)
```
![image](https://github.com/fawda123/EBASE/assets/3086881/a8e0ec34-ef86-472f-bb75-59587bd6d37c)

**Comment by sjbalint** [comment]
@fawda123 This looks great, thank you! Much appreciated
